/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_aeroraven_ifrit_IfritConsoleInterface */

#ifndef _Included_com_aeroraven_ifrit_IfritConsoleInterface
#define _Included_com_aeroraven_ifrit_IfritConsoleInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aeroraven_ifrit_IfritConsoleInterface
 * Method:    ICI_GetStdHandle
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_aeroraven_ifrit_IfritConsoleInterface_ICI_1GetStdHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_aeroraven_ifrit_IfritConsoleInterface
 * Method:    ICI_SetConsoleTextAttribute
 * Signature: (JS)Z
 */
JNIEXPORT jboolean JNICALL Java_com_aeroraven_ifrit_IfritConsoleInterface_ICI_1SetConsoleTextAttribute
  (JNIEnv *, jclass, jlong, jshort);

#ifdef __cplusplus
}
#endif
#endif
